services:
  spring:
    build:
      context: ./Atlascan_spring
      dockerfile: Dockerfile
    container_name: atlascan_spring
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
    env_file:
      - ./Atlascan_spring/.env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: atlascan_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: atlascan_db
      MYSQL_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
